#define NVIDIA_VRWORKS_GRAPHICS_VERSION_MAJOR 3
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_MINOR 2
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_RELEASE 9


#define NVIDIA_VRWORKS_GRAPHICS_VERSION 3,2,9,0
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_MAJOR_MINOR 3,2
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_STRING "3.2.9.0"
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_STRING_SHORT "3.2.9"
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_STRING_MAJOR_MINOR "3.2"
